### ISSUE TITLE
POM in NLP4J 1.1.1 does not use fixed version

### ISSUE THREAD

**Issue by reckart** [emorynlp/nlp4j-old#10]
I have upgraded the NLP4J dependency in my project to 1.1.1, but the transitive dependencies are still resolved to 1.1.0. This seems to be due to the fact that the POM of the nlp4j artifact does not use proper versions for its dependencies, but rather `RELEASE`:

```
<dependency>
<groupId>edu.emory.mathcs.nlp</groupId>
<artifactId>nlp4j-core</artifactId>
<version>RELEASE</version>
</dependency>
<dependency>
<groupId>edu.emory.mathcs.nlp</groupId>
<artifactId>nlp4j-tokenization</artifactId>
<version>RELEASE</version>
</dependency>
<dependency>
<groupId>edu.emory.mathcs.nlp</groupId>
<artifactId>nlp4j-morphology</artifactId>
<version>RELEASE</version>
</dependency>
```

It would be nice if proper versions would be used such that one doesn't have do add explicit versioned dependencies to their POMs for all the transitive NLP4J dependencies.

**Comment by jdchoi77** [comment]
I'll make this change for the following minor release.  Thanks for pointing out.
