### ISSUE TITLE
ClearNLP semantic Role Labelling + Entity Co referencing

### ISSUE THREAD

**Issue by ssetty** [emorynlp/nlp4j-old#11]
Hello,
 I have used clearNLP for semantic role labelling and entity coreferencing.

 (1)Entity corefence - resolves pron-nouns with proper nouns
 I am not clear about how to interpret output of coreferencing - basically I require entity names and set of sentences or sentence numbers associated with this. What are clusters here?

 rain@27.17         COMMON           UNKNOWN        SINGULAR
 Clusters:              [-1, -1, -1, 1, -1, -1, -1, -1, 7, 1, 9, -1, 10, -1, 9, -1
 Confidence:       [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

 ===== Clusters =====
 0: morning          (Singleton)
 3: He      ->       1: Stewart

 (2) How do interpret dependency parser output? Is there any documentation about labels used? Sometimes we see output with 7 slots and sometimes with 9 slots why? How TVRSReader recognise this?

 (3) Adding semantic role annotation adds an extra slot - how do link semantic role outputs?

 Thanks

**Comment by jdchoi77** [comment]
I think this issue is redundant to the thread opened in our group:

https://groups.google.com/forum/#!topic/emorynlp/yIlK0LW4A6A

Please follow up the thread.  Thanks.
