### ISSUE TITLE
Part-of-Speech Tagging example

### ISSUE THREAD

**Issue by kk00ss** [emorynlp/nlp4j-old#16]
For one of use cases I don't need syntax analysis or NER. I only need to get root forms for all words in a document. Could you please provide an example for POS tagging ?

**Comment by jdchoi77** [comment]
If you leave only the part-of-speech tagging model in the configuration file, it will run only up to part-of-speech tagging:

```
<models>
    <pos>edu/emory/mathcs/nlp/models/en-pos.xz</pos>
</models>
```

Please let me know if a more specific configuration is needed.  Thanks.

best,

Jinho
