### ISSUE TITLE
only POS tagger

### ISSUE THREAD

**Issue by deepcode-debug** [emorynlp/nlp4j-old#17]
Hi,

the command line tagging takes a lot of time,not suitable for real-time systems. Please provide API for single taggers like only for POS.

**Comment by jdchoi77** [comment]
What is your input format?  I believe [NLPDecoder](https://github.com/emorynlp/nlp4j/blob/master/src/main/java/edu/emory/mathcs/nlp/decode/NLPDecoder.java) can be used for this but if you let me know the format, I can provide more fine-grained API.

**Comment by deepcode-debug** [comment]
we are calling the decoder with a text file, it is taking around 2 mins 30
seconds to process

**Comment by jdchoi77** [comment]
I think most of the time is perhaps spent for model loading.  Here is the API you can use for this purpose:

https://github.com/emorynlp/nlp4j-demo/blob/master/src/main/java/edu/emory/mathcs/nlp/demo/NLPDecodeRaw.java

Here is the configuration file you can use just for pos tagging:
https://github.com/emorynlp/nlp4j-demo/blob/master/src/main/resources/configuration/config-decode-en-pos.xml

The following line loads all the models, which should be done only once:

```
NLPDecoder decoder = new NLPDecoder(IOUtils.getInputStream(configurationFile));
```

Thanks.

**Comment by deepcode-debug** [comment]
Thanks a lot for the reply, I will check and let you know if we have
further issues

Regards,
Debanjan
