### ISSUE TITLE
GlobalLexica unable to support multiple lexica

### ISSUE THREAD

**Issue by reckart** [emorynlp/nlp4j-old#2]
The static implementation of GlobalLexica prevents loading different types of lexica e.g. in a multi-threaded environment. Examples would be domain-specific lexica or lexica for different languages.

**Comment by jdchoi77** [comment]
I agree, this is something I should find a better solution for.  Thanks for pointing it out and I'll try to avoid static lexicons for the following version.

**Comment by jdchoi77** [comment]
The change has been made and will be applied to the next version.
