### ISSUE TITLE
Are components reentrant? Can components be cloned? 

### ISSUE THREAD

**Issue by benson-basis** [emorynlp/nlp4j-old#22]
It takes quite a while to decompress and deserialize a component, and we're going to need to do so often. If they are thread-safe, it's not an issue. if they can be cloned, it's not too bad, but the interface does not advertise this. Can you give me any advice? I can certainly dive into the code and start to look at how to modify it in this direction if needed.

**Comment by jdchoi77** [comment]
All NLP components are thread-safe; this change was made in the earlier version of ClearNLP, the predecessor of NLP4J, but now I realize not everyone knows about this so I should advertize it again.  Please let me know if this fixes your issue.  Thanks.

**Comment by benson-basis** [comment]
Wow, that will make some of my stuff a lot faster. Thank You.
