### ISSUE TITLE
CLI for Eval?

### ISSUE THREAD

**Issue by benson-basis** [emorynlp/nlp4j-old#27]
I went looking for a CLI for the Eval component, so that I could get scores for existing models. I didn't see one. If I'm right that it's not there, would you like a PR that creates one?

**Comment by jdchoi77** [comment]
You are right, there is no command line tool for evaluation; it existed at some point of ClearNLP but apparently didn't get to NLP4J :)  Sure, please let me know if you have questions while writing one.  Thanks!

**Comment by jdchoi77** [comment]
I just merged your evaluator (thanks).  I'm closing this issue.
