### ISSUE TITLE
Infinite recursion in AbstractNLPDecoder.createTSVReader()

### ISSUE THREAD

**Issue by benson-basis** [emorynlp/nlp4j-old#28]
I will shortly provide a PR that includes a test case and a fix for an infinite recursion in this method.

**Comment by jdchoi77** [comment]
Just merged your change.  I'm going to take off the dependency to the english models from the NLP4J pom.xml though.  This was left out intentionally for those who wanted to use NLP4J just for the APIs.  Thanks for the bugfix!

**Comment by benson-basis** [comment]
The dep is scope test, so it doesn't have any effect at runtime to people
who just want to use the API.

To take out the dep, you have to find another way to fire up the class to
run the test case. I'll be interested to see how you do it, perhaps it's
possible to make a more minimal configuration XML file than I realized.
