### ISSUE TITLE
Get fields from FeatureTemplate

### ISSUE THREAD

**Issue by reckart** [emorynlp/nlp4j-old#3]
It would be nice if there was a getter for the fields (/features) used in a feature template. The information can be crudely extracted from the toString() method (or using reflection), but a proper getter would be nicer.

**Comment by jdchoi77** [comment]
Could you give me an example of the aspect you're describing? Thanks.

**Comment by reckart** [comment]
I am building UIMA wrappers for NLP4J in DKPro Core. Here it is useful to check if
- a) the wrapper already supports all the features used by a model, e.g. to throw an exception if a model uses a feature in a feature template for which no conversion UIMA<->NLP4J has been implemented yet
- b) the features actually have been annotated in the document -, e.g. to throw an exception of the NLP4J dependency parser is invoked without first having annotated POS.

See for example:
- https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-nlp4j-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/nlp4j/internal/EmoryNlpUtils.java#L79
- https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-nlp4j-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/nlp4j/internal/EmoryNlpUtils.java#L101
- https://github.com/dkpro/dkpro-core/blob/master/dkpro-core-nlp4j-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/nlp4j/Nlp4JDependencyParser.java#L206

**Comment by jdchoi77** [comment]
Got it; I'll work on this for the next version as well.

**Comment by reckart** [comment]
Is this implemented in 1.1.0? It seems there is still no accessor method.

**Comment by jdchoi77** [comment]
Not yet, 1.1.0 release was not planned but I found a way of reducing the models, which was asked by so many people, so decided to make an early release.  I'll make a minor release (possibly, 1.1.1) for this change.  Thanks for reminder.

best,

Jinho

**Comment by jdchoi77** [comment]
Would something like this work for you?

https://github.com/emorynlp/nlp4j-core/blob/master/src/main/java/edu/emory/mathcs/nlp/component/template/feature/FeatureTemplate.java#L80
https://github.com/emorynlp/nlp4j-core/blob/master/src/main/java/edu/emory/mathcs/nlp/component/template/feature/FeatureTemplate.java#L85
https://github.com/emorynlp/nlp4j-core/blob/master/src/main/java/edu/emory/mathcs/nlp/component/template/feature/FeatureTemplate.java#L90

Please let me know if you need more methods.  I'm going to make the 1.1.1 release with this change once this gets resolved.  Thanks!

best,

Jinho

**Comment by reckart** [comment]
That should be working just nicely. Do you have a Maven repo with SNAPSHOT builds somewhere?

**Comment by jdchoi77** [comment]
I'm pushing a new release with this change now; will make the release note in few minutes.

**Comment by jdchoi77** [comment]
I'm closing this issue; please let me know if more things come up.  Thanks.
