### ISSUE TITLE
Static NLPDecoder.getComponent(InputStream)

### ISSUE THREAD

**Issue by reckart** [emorynlp/nlp4j-old#4]
The method NLPDecoder.getComponent(InputStream) could be static. It somehow feels like doing something wrong when first having to create an NLPDecoder instance without any configuration just in order to load a serialized component:

```
                NLPDecoder decoder = new NLPDecoder();
                OnlineComponent<POSState> component = (OnlineComponent<POSState>) 
                        decoder.getComponent(aStream);
```

**Comment by jdchoi77** [comment]
Done :) Will be included in the following version.
