### ISSUE TITLE
Where are the models?

### ISSUE THREAD

**Issue by abagshaw** [emorynlp/nlp4j-old#7]
I am trying to get a very basic dependency parser working (give it a sentence in a string and spit out the dependency tree).

I can't seem to find the models at the indicated location though:
https://bitbucket.org/emorynlp/nlp4j-english/src/fc6cf377142cb554ab74c7b6377eff6d28e43620/src/main/resources/edu/emory/mathcs/nlp/models/?at=master

Only `en-pos.xz` shows up there, no other models. Am I missing something?

Once I get all those models listed there I assume I'll use this:

https://github.com/emorynlp/nlp4j-demo/blob/master/src/main/java/edu/emory/mathcs/nlp/demo/DEPDecode.java

To get the dependency parser up and running? Do you have any better (quick-start-guide) kind of thing for getting the basic dependency parser up and running?

Also final question :) When is the ETA for SRL and Sentiment Analysis?

**Comment by jdchoi77** [comment]
I just realized that bitbucket changes the URL for each commit, which is pretty annoying :(  The easiest way of retrieving these models are through maven.

```
<dependency>
    <groupId>edu.emory.mathcs.nlp</groupId>
    <artifactId>nlp4j-english</artifactId>
    <version>1.0.0</version>
</dependency>
```

Please make sure you give about -Xmx8g.

Sentiment Analysis will most likely come by the end of April.  The SRL module is already implemented but I'm having some issues with the training data; I probably won't have time to fix this but it will definitely come by the end of May.

Please let me know you have any other question.  Take care.

best,

Jinho

**Comment by jdchoi77** [comment]
The latest models are updated here: https://bitbucket.org/emorynlp/nlp4j-english.  I'm closing this issue but please let me know if you have more questions.  Thaks.

best,

Jinho
