### ISSUE TITLE
Demo NLPDemo not working

### ISSUE THREAD

**Issue by nlp-fan** [emorynlp/nlp4j-old#8]
Hi, 
awesome project but I think a recent commit broke something, **NLPDemo** produces an error when I try to run it:

> Exception in thread "main" java.lang.NullPointerException
>   at edu.emory.mathcs.nlp.common.util.DSUtils.isRange(DSUtils.java:182)
>   at edu.emory.mathcs.nlp.component.template.node.AbstractNLPNode.getLeftMostDependent(AbstractNLPNode.java:545)
>   at edu.emory.mathcs.nlp.component.template.node.AbstractNLPNode.getLeftMostDependent(AbstractNLPNode.java:534)
>   at edu.emory.mathcs.nlp.component.template.node.AbstractNLPNode.getLeftValency(AbstractNLPNode.java:972)
>   at edu.emory.mathcs.nlp.component.template.node.AbstractNLPNode.getValency(AbstractNLPNode.java:959)
>   at edu.emory.mathcs.nlp.component.template.feature.FeatureTemplate.getFeature(FeatureTemplate.java:301)
>   at edu.emory.mathcs.nlp.component.template.feature.FeatureTemplate.getFeature(FeatureTemplate.java:288)
>   at edu.emory.mathcs.nlp.component.template.feature.FeatureTemplate.getFeature(FeatureTemplate.java:276)
>   at edu.emory.mathcs.nlp.component.template.feature.FeatureTemplate.createSparseVector(FeatureTemplate.java:239)
>   at edu.emory.mathcs.nlp.component.template.feature.FeatureTemplate.createFeatureVector(FeatureTemplate.java:221)
>   at edu.emory.mathcs.nlp.component.template.OnlineComponent.process(OnlineComponent.java:194)
>   at edu.emory.mathcs.nlp.component.template.OnlineComponent.process(OnlineComponent.java:172)
>   at edu.emory.mathcs.nlp.decode.AbstractNLPDecoder.decode(AbstractNLPDecoder.java:286)
>   at edu.emory.mathcs.nlp.decode.AbstractNLPDecoder.decode(AbstractNLPDecoder.java:280)
>   at edu.emory.mathcs.nlp.bin.NLPDemo.main(NLPDemo.java:38)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by nlp-fan** [comment]
Does a previous version work, I'd like to try this project...

**Comment by jdchoi77** [comment]
Sorry, I'm making some internal changes on the main branch; I'm going to make another release sometime soon (within a week potentially), so please stay tuned.  Please let me know if this is rather urgent.  Thanks.

best,

Jinho

**Comment by jdchoi77** [comment]
I just pushed a new release: 1.1.0.  Could you please try with the new release?  Thanks.

best,

Jinho
